project:
  type: website

website:
  page-navigation: true
  repo-url: https://github.com/JoseBlanca/intro_programing_python
  repo-actions: [source, issue]
  title: "Introduction to programming with Python"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Basics"
        contents:
          - text: "Hello world"
            href: intro/hello_world.qmd
          - text: "Flow and variables"
            href: intro/flow_and_variables.qmd
      - section: "Types and operators"
        contents:
          - text: "Types"
            href: types_and_operators/types.qmd
          - text: "Operators"
            href: types_and_operators/operators.qmd
          - text: "Comparisons and bool operators"
            href: types_and_operators/comparisons_and_bool_operators.qmd
          - text: "Strings"
            href: types_and_operators/strings.qmd
      - section: "Compound types"
        contents:
          - text: "Lists"
            href: types_and_operators/lists.qmd
          - text: "Dictionaries"
            href: types_and_operators/dictionaries.qmd
      - section: "Control flow"
        href: control_flow/index.qmd
        contents:
          - text: "if"
            href: control_flow/if.qmd
          - text: "for loops"
            href: control_flow/for.qmd
          - text: "Code blocks"
            href: control_flow/block.qmd
      - section: "Exercises"
        contents:
          - text: "Exercises"
            href: exercises/set1.qmd
      - section: "Functions"
        contents:
          - text: "Definition"
            href: functions/definition.qmd
          - text: "More on functions"
            href: functions/more_on_functions.qmd
      - section: "Exercises"
        contents:
          - text: "Exercises 2"
            href: exercises/set2.qmd
      - section: "Install and run Python"
        contents:
          - text: "Install"
            href: local_install/run_python.qmd
          - text: "Local hello world"
            href: local_install/hello_world2.qmd
      - section: "Files"
        contents:
          - text: "Read & write"
            href: files/read_write.qmd
      - section: "Modules and packages"
        contents:
          - text: Modules
            href: packages/modules.qmd
          - text: Standard library
            href: packages/std_library.qmd
      - section: "Exceptions"
        contents:
          - text: "Exceptions"
            href: exceptions.qmd
      - section: "Exercises 3"
        contents:
          - text: "Exercises"
            href: exercises/set3.qmd
      - section: "Everyday Python"
        contents:
          - text: "Everyday Python"
            href: everyday_python/everyday_python.qmd
          - text: Typing
            href: everyday_python/typing.qmd
          - section: "Loop utilities"
            contents:
            - text: range
              href: everyday_python/range.qmd
            - text: enumerate
              href: everyday_python/enumerate.qmd
            - text: zip
              href: everyday_python/zip.qmd
          - section: "File utilities"
            contents:
            - text: "Paths"
              href: everyday_python/paths.qmd
            - text: "shutil"
              href: everyday_python/shutil.qmd
          - text: "subprocess"
            href: everyday_python/subprocess.qmd
          - text: "Comprehensions"
            href: everyday_python/comprehensions.qmd
          - text: "Counter"
            href: everyday_python/collections.qmd
          - text: "lambda"
            href: everyday_python/lambda.qmd  
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/JoseBlanca/intro_programing_python
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
